---
include:
  - https://gitlab.exphost.pl/exphost/exphost-helms/-/raw/master/common/gitlab-ci.yml
stages:
  - upload
#  - deploy

upload:
  extends: .upload
#nodes:
#  stage: deploy
#  image: alpine
#  before_script:
#    - apk add --no-cache ca-certificates git curl yq
#    - curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl
#    - chmod +x /usr/local/bin/kubectl
#  script:
#    - export VERSION=$(git describe --tags)
#    - kubectl -n argocd get applications exphost -o 'jsonpath={.spec.source.helm.values}' > /tmp/values.yaml
#    - VALUES=$(yq eval  ".exphostConfigurator.version=\"$VERSION\"" /tmp/values.yaml|awk '{printf "%s\\n", $0}' | sed 's/"/\\"/g' )
#    - kubectl patch application -n argocd exphost --patch="{\"spec\":{\"source\":{\"helm\":{\"values\":\"${VALUES}\"}}}}" --type=merge
#  environment:
#    name: dev
