apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exphost-configurator
rules:
- apiGroups: ["*"]
  resources: ["secrets", "configmaps", "events","clusterrolebindings"]
  verbs: ["list", "create"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings"]
  verbs: ["list", "create"]
