apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exphost-configurator
rules:
- apiGroups: ["*"]
  resources: ["secrets", "configmaps", "events"]
  verbs: ["list", "create"]
