apiVersion: v1
kind: Service
metadata:
  name: exphost-configurator
spec:
  ports:
    - name: http
      port: 30070
      targetPort: http
      type: NodePort
  selector:
    app: exphost-configurator
