apiVersion: v1
kind: Service
metadata:
  name: exphost-configurator
spec:
  ports:
    - name: http
      nodePort: 30070
      port: 8080
      targetPort: http
  type: NodePort
  selector:
    app: exphost-configurator
